pub const PRODUCT_BLOCK_LIST: &[&str] = &[
    "ambrée",
    "apple cider",
    "biere",
    "biere blonde",
    "bière",
    "bière ambrée",
    "bière blanche",
    "bière blonde",
    "birra",
    "blonde",
    "cabernet sauvignon",
    "cerveza",
    "cerveza lager",
    "champagne",
    "champagne brut",
    "chardonnay",
    "cidre",
    "cidre bio",
    "cidre brut",
    "cidre doux",
    "cidre rosé",
    "cognac",
    "gin",
    "grappa",
    "hard seltzer",
    "helles",
    "india pale ale",
    "irish red ale",
    "lager",
    "lager beer",
    "london dry gin",
    "moscato",
    "natur radler",
    "pale ale",
    "panaché",
    "pils",
    "pilsner",
    "prosecco",
    "radler",
    "red wine",
    "rhum",
    "rose",
    "rosé",
    "sangria",
    "sauvignon",
    "sauvignon blanc",
    "shandy",
    "sidra",
    "tequila",
    "vin",
    "vin blanc",
    "vin blanc sec",
    "vin rosé",
    "vin rouge",
    "vino",
    "vino blanco",
    "vino rosso",
    "vino tinto",
    "vodka",
    "wine"
];
